# Generated by Django 5.0.2 on 2025-12-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0004_eventosacademicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
