# Generated by Django 5.0.2 on 2025-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0005_add_edad_to_maestros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
